spring:
  application:
    name: api-entreprise

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: api-user  # L'URL de votre service OAuth
          jwk-set-uri: http://api-user:8083/oauth/jwks  # Endpoint pour obtenir les clés publiques pour valider les JWT
          # jwk-set-uri: http://localhost:8083/oauth/jwks  # Endpoint pour obtenir les clés publiques pour valider les JWT

  config:
    import: optional:configserver:http://ms-config:8888
    # import: optional:configserver:http://localhost:8888
    cloud:
      config:
        enabled: true  # Utilisation des propriétés locales si Config Server est indisponible
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # url: jdbc:mariadb://mariadb:3306/Jcaisse_entreprise?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    url: jdbc:mariadb://mariadb-api-entreprise:3306/Jcaisse_entreprise?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: root
    username: root
    password: yaatout
  jpa:
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true

  kafka:
    bootstrap-servers: 31.220.20.148:9094  # Adresse Kafka distante
    consumer:
      group-id: group_id

management:
  endpoints:
    web:
      exposure:
        include: '*'  # Expose tous les endpoints pour l'administration

server:
  port: 8081  # Port de l'application


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.nimbusds: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG

eureka:
  instance:
    prefer-ip-address: true  # Utiliser l'adresse IP au lieu du nom d'hôte
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://ms-register:8761/eureka/}  # URL de Eureka avec fallback
      # defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
