spring:
  application:
    name: api-gestion-candidature
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 40MB
  mvc:
    servlet:
      path: /api/startup
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: BINARY
server:
  port: 8092
management:
  endpoints:
    web:
      exposure:
        include: "health,info,gateway"
  endpoint:
    gateway:
      enabled: true
  health:
    show-details: always
  app:
    jwtSecret: samaMbote#413F4428472B4B6250655368566D5970337336763979244226452948404D6351
    jwtExpirationMs: 86400000
documents:
  directory: /app/documents
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.nimbusds: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG

---
# ---------- PROFIL DOCKER (TEST) ----------
spring:
  config:
    activate:
      on-profile: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://depinfo-dev.tech/api/user/gestionCandidature/oauth/jwks
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
eureka:
  client:
    service-url:
      defaultZone: http://ms-register:8093/eureka/

---
# ---------- PROFIL PROD ----------
spring:
  config:
    activate:
      on-profile: prod
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://depinfo-dev.tech/api/user/gestionCandidature/oauth/jwks
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
eureka:
  client:
    service-url:
      defaultZone: http://ms-register-gestion-candidature:8093/eureka/

---
# ---------- PROFIL LOCAL ----------
spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8091/api/user/gestionCandidature/oauth/jwks
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/gestionCandidat?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: daos
    password: daos
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8093/eureka/
