# ---------- Profil Docker ----------
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  eureka:
    client:
      service-url:
        defaultZone: http://ms-register:8093/eureka/

---
# ---------- Profil Prod ----------
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  eureka:
    client:
      service-url:
        defaultZone: http://ms-register-gestion-candidature:8093/eureka/

---
# ---------- Profil Local ----------
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/gestionCandidat_user?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: daos
    password: daos
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8093/eureka/
