# ------------------------------------
# Configuration par défaut
# ------------------------------------
spring:
  application:
    name: maquette-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8094

management:
  endpoints:
    web:
      exposure:
        include: "health,info,gateway"
  endpoint:
    gateway:
      enabled: true
  health:
    show-details: always

---
# ------------------------------------
# Profil Docker (TEST)
# ------------------------------------
spring:
  config:
    activate:
      on-profile: docker
  security:
    oauth2:
      client:
        registration:
          ms-maquette:
            provider: api-user
            client-id: ms-maquette
            client-secret: ms-maquette-secret
            authorization-grant-type: client_credentials
            scope: read,write
        provider:
          api-user:
            token-uri: https://depinfo-dev.tech/api/user/gestionCandidature/oauth/token
      resourceserver:
        jwt:
          jwk-set-uri: https://depinfo-dev.tech/api/user/gestionCandidature/oauth/jwks
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  eureka:
    client:
      enabled: false
      # service-url:
      #   defaultZone: http://ms-register:8093/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

---
# ------------------------------------
# Profil Prod
# ------------------------------------
spring:
  config:
    activate:
      on-profile: prod
  security:
    oauth2:
      client:
        registration:
          ms-maquette:
            provider: api-user
            client-id: ms-maquette
            client-secret: ms-maquette-secret
            authorization-grant-type: client_credentials
            scope: read,write
        provider:
          api-user:
            token-uri: https://depinfo-dev.tech/api/user/gestionCandidature/oauth/token
      resourceserver:
        jwt:
          jwk-set-uri: https://depinfo-dev.tech/api/user/gestionCandidature/oauth/jwks
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  eureka:
    client:
      enabled: false
      # service-url:
      #   defaultZone: http://ms-register-gestion-candidature:8093/eureka/

---
# ------------------------------------
# Profil Local
# ------------------------------------
spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8091/api/user/gestionCandidature/oauth/jwks
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/gestionMaquette?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: daos
    password: daos
  eureka:
    client:
      enabled: false
      # service-url:
      #   defaultZone: http://localhost:8093/eureka/
