
#   # security:
#   #   oauth2:
#   #     resourceserver:
#   #       jwt:
#   #         issuer-uri: http://api-user:8091/yaatout/auth  # Remplacez par l'URI de votre serveur d'authentification
  

#   config:
# #    import: optional:configserver:http://localhost:8888
#     import: optional:configserver:http://ms-config:8894

server:
  port: 8090

spring:
  application:
    name: ms-proxy
    #   # security:
#   #   oauth2:
#   #     resourceserver:
#   #       jwt:
#   #         issuer-uri: http://api-user:8091/yaatout/auth  # Remplacez par l'URI de votre serveur d'authentification

  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        enabled: true  # Active la découverte de services via Eureka
        locator:
          enabled: true  # Permet au Gateway de localiser les services via Eureka
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000, http://31.220.20.148:3093"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - PATCH
            - DELETE
            - PUT
            - OPTIONS
      routes:
      #   - id: maquette-service
      #     uri: http://localhost:8081/
      #     predicates:
      #       - Path=/**
      #   - id: repartition-service
      #     uri: http://localhost:8082/
      #     predicates:
      #       - Path=/**
      #   - id: emploiDutemps-service
      #     uri: http://localhost:8083/
      #     predicates:
      #       - Path=/**

  main:
    web-application-type: reactive
    # allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://ms-register:8093/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,gateway"
  endpoint:
    gateway:
      enabled: true
  health:
    show-details: always
# Configuration de log
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: TRACE
