# Activer la découverte des services Eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.discovery.locator.routes.use-service-id-as-prefix=true

# Exposition des endpoints pour la gestion
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.enabled=true
management.health.show-details=always

# Port du serveur Gateway
server.port=8090

# Configuration de Eureka
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${EUREKA_URI:http://ms-register:8093/eureka/}

# Application réactive (WebFlux)
spring.main.web-application-type=reactive

# Configuration de log
logging.level.org.springframework.cloud.gateway=DEBUG
