# Activer la découverte des services Eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.discovery.locator.routes.use-service-id-as-prefix=true

# Exposition des endpoints pour la gestion
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.enabled=true
management.health.show-details=always

# Port du serveur Gateway
server.port=8090

# Configuration de Eureka
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${EUREKA_URI:http://ms-register:8093/eureka/}

# Application réactive (WebFlux)
spring.main.web-application-type=reactive

# Configuration de log
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.com.netflix.discovery=DEBUG

spring.cloud.gateway.http.client.response-timeout=10s  # Augmentez ce délai si nécessaire
spring.cloud.gateway.http.client.connect-timeout=10s  # Augmentez également ce délai




# Route vers MS-PROXY
spring.cloud.gateway.routes[0].id=ReactiveCompositeDiscoveryClient_MS-PROXY
spring.cloud.gateway.routes[0].uri=lb://MS-PROXY
spring.cloud.gateway.routes[0].predicates[0]=Path=/ms-proxy/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/ms-proxy/(?<remaining>.*), /${remaining}

# Route vers API-GESTION-CANDIDATURE
spring.cloud.gateway.routes[1].id=ReactiveCompositeDiscoveryClient_API-GESTION-CANDIDATURE
spring.cloud.gateway.routes[1].uri=lb://API-GESTION-CANDIDATURE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api-gestion-candidature/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api-gestion-candidature/(?<remaining>.*), /${remaining}

# Route vers API-USER
spring.cloud.gateway.routes[2].id=ReactiveCompositeDiscoveryClient_API-USER
spring.cloud.gateway.routes[2].uri=lb://API-USER
spring.cloud.gateway.routes[2].predicates[0]=Path=/api-user/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/api-user/(?<remaining>.*), /${remaining}

# Route vers MAQUETTE-SERVICE
spring.cloud.gateway.routes[3].id=ReactiveCompositeDiscoveryClient_MAQUETTE-SERVICE
spring.cloud.gateway.routes[3].uri=lb://MAQUETTE-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/maquette-service/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/maquette-service/(?<remaining>.*), /${remaining}



spring.cloud.gateway.filters[0]=Retry=3  # Nombre de tentatives de réessai
