spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.discovery.locator.routes.use-service-id-as-prefix=true
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.enabled=true
management.health.show-details=always


server.port=8090
